/**
 * Plugin implementation — your-new-plugin
 * ========================================
 *
 * This file is the core of your plugin. Follow the numbered sections below
 * to implement your own slash command.
 *
 * WHAT THIS TEMPLATE DOES:
 *   /greeting [name]  — responds with a personalised greeting card
 *   /greeting doc [name] — creates a Feishu Doc draft with the greeting content
 *
 * REPLACE THIS ENTIRE FILE with your own logic. Keep the structure (imports,
 * your handler functions, and the `plugin` export) as the skeleton.
 */

import type {
  FeishuPlugin,
  PluginCommandResult,
  PluginRegistry,
  WorkflowResult,
} from '../../core/plugin-system.js';
import type { FeishuMessageEvent } from '../../types/feishu-event.js';
import type { AppConfig } from '../../config/load-config.js';
import type { WorkflowOptions } from '../../workflows/run-message-workflow.js';

// ─── SECTION 1: Configuration ────────────────────────────────────────────────
//
// Define your plugin's environment-variable names here. Document them in
// .env.example so operators know what to set. Access via process.env at
// runtime (the plugin runs in the same Node.js process as the server).
//
// const MY_PLUGIN_API_KEY = process.env.MY_PLUGIN_API_KEY;

// ─── SECTION 2: Helper functions ─────────────────────────────────────────────
//
// Keep your business logic separate from the lifecycle hooks. Pure functions
// here make testing easy (just call them with mock inputs).

function buildGreetingCard(name: string): object {
  const displayName = name.trim() || 'friend';
  return {
    msg_type: 'interactive',
    card: {
      header: {
        title: { tag: 'plain_text', content: `👋 Hello, ${displayName}!` },
        template: 'green',
      },
      elements: [
        {
          tag: 'markdown',
          content: `Welcome to **feishu-flow-kit**! Your plugin is running.`,
        },
        { tag: 'hr' },
        {
          tag: 'markdown',
          content:
            '📖 **Next steps**\n' +
            '1. Edit `plugins/template/plugin.ts`\n' +
            '2. Run `node scripts/create-plugin.mjs your-plugin-name`\n' +
            '3. Add your module path to `FEISHU_PLUGINS` in `.env`\n' +
            '4. Restart the server — your command is live!',
        },
      ],
    },
  };
}

function buildGreetingDoc(name: string): { topic: string; markdown: string } {
  const displayName = name.trim() || 'friend';
  return {
    topic: `Greeting Document — ${displayName}`,
    markdown:
      `# Greeting for ${displayName}\n\n` +
      `> Generated by the feishu-flow-kit plugin template.\n\n` +
      `## Welcome!\n\n` +
      `This document was created by the \`/greeting\` plugin.\n\n` +
      `## What next?\n\n` +
      `- Replace this content with your own\n` +
      `- Add more sections\n` +
      `- Connect to your API or database\n`,
  };
}

// ─── SECTION 3: The plugin object ────────────────────────────────────────────
//
// `plugin` is the only thing the plugin system needs. It conforms to
// `FeishuPlugin` and uses the `createPlugin` factory pattern (recommended
// over the named export when your plugin needs config at startup).

export function createPlugin(_config: AppConfig): FeishuPlugin {
  return {
    name: 'template', // ← MUST be unique across all loaded plugins

    // ── register() — claim your slash command name(s) ───────────────────────
    //
    // Called once on server startup. Register every /command you handle here.
    // If two plugins register the same name, the first one wins (no override).
    register(registry: PluginRegistry) {
      registry.registerCommand('greeting', pluginInstance);
    },

    // ── beforeProcess() — pre-filter events (optional) ───────────────────────
    //
    // Return `false` to skip the entire workflow for this event.
    // Good for: filtering by sender, language, content type, etc.
    beforeProcess(event: FeishuMessageEvent): boolean | void {
      // Example: skip non-text messages
      // if (event.message?.message_type !== 'text') return false;
      return; // proceed normally
    },

    // ── handle() — your slash command handler ───────────────────────────────
    //
    // Return `null` to defer to the next handler (built-in or later plugin).
    // Return a `PluginCommandResult` to produce a reply.
    handle(
      command: { name: string; argsText: string },
      event: FeishuMessageEvent,
      _options: WorkflowOptions,
    ): PluginCommandResult | null {
      if (command.name !== 'greeting') return null;

      const args = command.argsText.trim();
      const isDocMode = args.startsWith('doc ');
      const name = isDocMode ? args.slice(4).trim() : args;

      if (isDocMode) {
        // Return a doc creation draft instead of a text reply
        const doc = buildGreetingDoc(name);
        return {
          ok: true,
          replyText: `📄 Creating greeting document for *${name || 'friend'}*…`,
          tags: ['greeting', 'plugin', 'doc'],
          hasDocCreateDraft: true,
          docTopic: doc.topic,
          docMarkdown: doc.markdown,
        };
      }

      // Standard text reply: send a Feishu interactive card
      const card = buildGreetingCard(name);
      return {
        ok: true,
        replyText: JSON.stringify(card, null, 2),
        tags: ['greeting', 'plugin'],
      };
    },

    // ── onCommandResult() — intercept built-in results (optional) ───────────
    //
    // Mutate `result.replyText` or `result.tags` in place.
    // Throw to abort and replace the reply with an error message.
    onCommandResult(result: WorkflowResult, event: FeishuMessageEvent): void {
      // Example: append a signature to every reply
      // result.replyText += '\n\n— sent via feishu-flow-kit';
    },

    // ── afterProcess() — fire-and-forget side-effects (optional) ─────────────
    //
    // Runs after all handlers have finished. Errors are caught and logged
    // but will not crash the webhook response.
    afterProcess(event: FeishuMessageEvent, result: WorkflowResult): void {
      // Example: forward to an external analytics webhook
      // fetch('https://analytics.example.com/hook', {
      //   method: 'POST',
      //   headers: { 'Content-Type': 'application/json' },
      //   body: JSON.stringify({ user: event.sender.sender_id, command: result.tags }),
      // }).catch(() => {}); // fire-and-forget
    },
  };
}

// Singleton instance used by register() — needed because register() receives
// the registry BEFORE handle() is ever called, so we can't rely on `this`.
const pluginInstance: FeishuPlugin = createPlugin({} as AppConfig);
