/**
 * Plugin implementation — your-new-plugin
 * ========================================
 *
 * This file is the core of your plugin. Follow the numbered sections below
 * to implement your own slash command.
 *
 * WHAT THIS TEMPLATE DOES:
 *   /greeting [name]  — responds with a personalised greeting card
 *   /greeting doc [name] — creates a Feishu Doc draft with the greeting content
 *
 * REPLACE THIS ENTIRE FILE with your own logic. Keep the structure (imports,
 * your handler functions, and the `createPlugin` export) as the skeleton.
 */

import type {
  FeishuPlugin,
  PluginCommandResult,
  PluginRegistry,
  WorkflowResult,
  WorkflowOptions,
  FeishuMessageEvent,
  AppConfig,
} from './types.js';

// ─── SECTION 1: Configuration ────────────────────────────────────────────────
//
// Define your plugin's environment-variable names here. Document them in
// .env.example so operators know what to set. Access via process.env at
// runtime (the plugin runs in the same Node.js process as the server).
//
// const MY_PLUGIN_API_KEY = process.env.MY_PLUGIN_API_KEY;

// ─── SECTION 2: Helper functions ─────────────────────────────────────────────
//
// Keep your business logic separate from the lifecycle hooks. Pure functions
// here make testing easy (just call them with mock inputs).

function buildGreetingCard(name: string): object {
  const displayName = name.trim() || 'friend';
  return {
    msg_type: 'interactive',
    card: {
      header: {
        title: { tag: 'plain_text', content: `👋 Hello, ${displayName}!` },
        template: 'green',
      },
      elements: [
        {
          tag: 'markdown',
          content: `Welcome to **feishu-flow-kit**! Your plugin is running.`,
        },
        { tag: 'hr' },
        {
          tag: 'markdown',
          content:
            '📖 **Next steps**\n' +
            '1. Edit `plugins/template/plugin.ts`\n' +
            '2. Run `node scripts/create-plugin.mjs your-plugin-name`\n' +
            '3. Add your module path to `FEISHU_PLUGINS` in `.env`\n' +
            '4. Restart the server — your command is live!',
        },
      ],
    },
  };
}

function buildGreetingDoc(name: string): { topic: string; markdown: string } {
  const displayName = name.trim() || 'friend';
  return {
    topic: `Greeting Document — ${displayName}`,
    markdown:
      `# Greeting for ${displayName}\n\n` +
      `> Generated by the feishu-flow-kit plugin template.\n\n` +
      `## Welcome!\n\n` +
      `This document was created by the \`/greeting\` plugin.\n\n` +
      `## What next?\n\n` +
      `- Replace this content with your own\n` +
      `- Add more sections\n` +
      `- Connect to your API or database\n`,
  };
}

// ─── SECTION 3: The plugin object ────────────────────────────────────────────
//
// `createPlugin` is the recommended factory pattern — use it when your plugin
// needs config at startup. For stateless plugins you can also use a named
// `export const plugin: FeishuPlugin = { ... }`.

export function createPlugin(_config: AppConfig): FeishuPlugin {
  return {
    name: 'template', // ← MUST be unique across all loaded plugins

    // ── register() — claim your slash command name(s) ───────────────────────
    register(registry: PluginRegistry) {
      registry.registerCommand('greeting', pluginInstance);
    },

    // ── beforeProcess() — pre-filter events (optional) ─────────────────────
    beforeProcess(_event: FeishuMessageEvent): boolean | void {
      return; // proceed normally
    },

    // ── handle() — your slash command handler ───────────────────────────────
    handle(
      command: { name: string; argsText: string },
      _event: FeishuMessageEvent,
      _options: WorkflowOptions,
    ): PluginCommandResult | null {
      if (command.name !== 'greeting') return null;

      const args = command.argsText.trim();
      const isDocMode = args.startsWith('doc ');
      const name = isDocMode ? args.slice(4).trim() : args;

      if (isDocMode) {
        const doc = buildGreetingDoc(name);
        return {
          ok: true,
          replyText: `📄 Creating greeting document for *${name || 'friend'}*…`,
          tags: ['greeting', 'plugin', 'doc'],
          hasDocCreateDraft: true,
          docTopic: doc.topic,
          docMarkdown: doc.markdown,
        };
      }

      const card = buildGreetingCard(name);
      return {
        ok: true,
        replyText: JSON.stringify(card, null, 2),
        tags: ['greeting', 'plugin'],
      };
    },

    // ── onCommandResult() — intercept built-in results (optional) ───────────
    onCommandResult(_result: WorkflowResult, _event: FeishuMessageEvent): void {
      // Example: append a signature
      // _result.replyText += '\n\n— sent via feishu-flow-kit';
    },

    // ── afterProcess() — fire-and-forget side-effects (optional) ─────────────
    afterProcess(_event: FeishuMessageEvent, _result: WorkflowResult): void {
      // Example: forward to an analytics webhook
      // fetch('https://analytics.example.com/hook', { method: 'POST', body: JSON.stringify({}) }).catch(() => {});
    },
  };
}

// Singleton instance used by register() — needed because register() receives
// the registry BEFORE handle() is ever called, so we can't rely on `this`.
const pluginInstance: FeishuPlugin = createPlugin({} as AppConfig);

// Named export so `import { plugin } from '@feishu/plugin-template'` works too.
export { pluginInstance as plugin };
